mgc_api_key = "MGC_API_KEY"
mgc_api_key_id = "MGC_API_KEY_ID"
mgc_api_key_secret = "MGC_API_KEY_SECRET"
mgc_region = "MGC_REGION"
mgc_env = "MGC_ENV"
vm_size = "VM_SIZE"
db_username = "DB_USERNAME"
db_password = "DB_PASSWORD"
